export interface Place {
  name: string;
  category: "Landmark" | "Museum" | "Nature" | "Beach" | "Historic" | "Entertainment" | "Religious" | "Park";
  description: string;
  city: string;
  pexelsQuery?: string;
}

export const PLACES_BATCH_1: Record<string, Place[]> = {
  FRA: [
    {
      name: "Eiffel Tower",
      category: "Landmark",
      description: "The iconic iron lattice tower on the Champ de Mars is France's most recognizable symbol and the world's most visited paid monument. Built in 1889 for the World's Fair, it stands 330 meters tall and offers sweeping views of Paris.",
      city: "Paris",
      pexelsQuery: "Eiffel Tower Paris",
    },
    {
      name: "Louvre Museum",
      category: "Museum",
      description: "The world's largest art museum and a historic monument, housing over 380,000 objects including the Mona Lisa and the Venus de Milo. Its iconic glass pyramid entrance has become a landmark in its own right.",
      city: "Paris",
      pexelsQuery: "Louvre Museum Paris pyramid",
    },
    {
      name: "Mont Saint-Michel",
      category: "Historic",
      description: "A stunning island commune topped by a medieval abbey that rises dramatically from the sea in Normandy. Accessible by a causeway, the tidal island transforms with the rise and fall of the surrounding waters.",
      city: "Normandy",
      pexelsQuery: "Mont Saint-Michel island abbey",
    },
    {
      name: "Palace of Versailles",
      category: "Historic",
      description: "The opulent royal chateau built by Louis XIV that served as the political center of France for over a century. Its Hall of Mirrors and meticulously landscaped gardens spanning 800 hectares are unmatched in grandeur.",
      city: "Versailles",
      pexelsQuery: "Palace of Versailles gardens",
    },
    {
      name: "French Riviera",
      category: "Beach",
      description: "The glamorous Mediterranean coastline stretching from Menton to Saint-Tropez, dotted with chic resorts, azure waters, and sun-drenched promenades. Nice, Cannes, and Monaco are its most celebrated destinations.",
      city: "Nice",
      pexelsQuery: "French Riviera Cote d Azur beach",
    },
    {
      name: "Notre-Dame Cathedral",
      category: "Religious",
      description: "A masterpiece of Gothic architecture on the Ile de la Cite that has stood at the heart of Paris for over 850 years. Following the devastating 2019 fire, it reopened in 2024 after a painstaking restoration.",
      city: "Paris",
      pexelsQuery: "Notre-Dame Cathedral Paris",
    },
  ],

  ESP: [
    {
      name: "Sagrada Familia",
      category: "Religious",
      description: "Antoni Gaudi's extraordinary basilica in Barcelona, under construction since 1882, blends Gothic and Art Nouveau styles into a breathtaking organic form. Its towering spires and kaleidoscopic interior light make it the most visited monument in Spain.",
      city: "Barcelona",
      pexelsQuery: "Sagrada Familia Barcelona Gaudi",
    },
    {
      name: "Alhambra",
      category: "Historic",
      description: "A magnificent Moorish palace and fortress complex perched above Granada, featuring intricate tilework, carved stucco, and serene courtyard gardens. It stands as one of the finest surviving examples of Islamic architecture in the world.",
      city: "Granada",
      pexelsQuery: "Alhambra palace Granada Spain",
    },
    {
      name: "Park Guell",
      category: "Park",
      description: "Gaudi's colorful hilltop park in Barcelona is a UNESCO World Heritage Site renowned for its mosaic-covered terraces, gingerbread gatehouses, and panoramic views over the city. Conceived as a garden city, it was later gifted to Barcelona as a public park.",
      city: "Barcelona",
      pexelsQuery: "Park Guell Barcelona mosaic",
    },
    {
      name: "Prado Museum",
      category: "Museum",
      description: "Spain's national art museum in Madrid holds one of the world's finest collections of European paintings, including masterworks by Velazquez, Goya, and El Greco. Its galleries house over 8,000 paintings spanning the 12th to early 20th centuries.",
      city: "Madrid",
      pexelsQuery: "Prado Museum Madrid art",
    },
    {
      name: "Balearic Islands",
      category: "Beach",
      description: "An archipelago in the western Mediterranean comprising Mallorca, Menorca, Ibiza, and Formentera, each offering crystal-clear turquoise waters and pristine sandy coves. The islands attract millions of visitors annually with their mix of nightlife, culture, and natural beauty.",
      city: "Palma de Mallorca",
      pexelsQuery: "Mallorca beach turquoise water Spain",
    },
    {
      name: "Seville Cathedral",
      category: "Religious",
      description: "The largest Gothic cathedral in the world and a UNESCO World Heritage Site, built on the site of a former mosque and home to Christopher Columbus's tomb. Its iconic Giralda bell tower, once a Moorish minaret, is Seville's defining skyline feature.",
      city: "Seville",
      pexelsQuery: "Seville Cathedral Giralda tower",
    },
  ],

  USA: [
    {
      name: "Grand Canyon",
      category: "Nature",
      description: "One of Earth's greatest natural wonders, the Grand Canyon stretches 446 km long and over 1.6 km deep, revealing two billion years of geological history in its layered red rock walls. Millions visit each year to hike its trails, raft the Colorado River, or simply stand in awe at the rim.",
      city: "Grand Canyon Village, Arizona",
      pexelsQuery: "Grand Canyon Arizona landscape",
    },
    {
      name: "Statue of Liberty",
      category: "Landmark",
      description: "A colossal neoclassical sculpture gifted by France to the United States, standing on Liberty Island in New York Harbor since 1886. The copper statue, a universal symbol of freedom, welcomes visitors who can climb to the crown for views of Manhattan.",
      city: "New York City, New York",
      pexelsQuery: "Statue of Liberty New York Harbor",
    },
    {
      name: "Yellowstone National Park",
      category: "Nature",
      description: "America's first national park sits atop one of the world's largest volcanic systems, fueling thousands of geysers, hot springs, and mud pots including the famous Old Faithful. The park also shelters diverse megafauna including bison, wolves, and grizzly bears.",
      city: "Wyoming",
      pexelsQuery: "Yellowstone geyser Old Faithful",
    },
    {
      name: "The Metropolitan Museum of Art",
      category: "Museum",
      description: "The Met is the largest art museum in the Western Hemisphere, holding a permanent collection of over two million works spanning 5,000 years of culture across every medium. Its iconic Fifth Avenue facade anchors Museum Mile in Manhattan.",
      city: "New York City, New York",
      pexelsQuery: "Metropolitan Museum of Art New York",
    },
    {
      name: "Hawaii Volcanoes National Park",
      category: "Nature",
      description: "This remarkable park on the Big Island of Hawaii encompasses two of the world's most active volcanoes, Kilauea and Mauna Loa, offering visitors a rare chance to witness lava flows and volcanic landscapes up close. UNESCO designated it a World Heritage Site for its outstanding geological and ecological significance.",
      city: "Hawaii Island, Hawaii",
      pexelsQuery: "Hawaii volcano lava national park",
    },
    {
      name: "Times Square",
      category: "Entertainment",
      description: "The electrifying commercial and entertainment hub of Midtown Manhattan, blazing with massive LED billboards, Broadway theaters, and around-the-clock crowds of over 50 million visitors per year. It hosts the famous New Year's Eve ball drop, broadcast to audiences worldwide.",
      city: "New York City, New York",
      pexelsQuery: "Times Square New York City night lights",
    },
  ],

  ITA: [
    {
      name: "Colosseum",
      category: "Historic",
      description: "The world's largest ancient amphitheater, completed in 80 AD, once hosted gladiatorial contests and public spectacles for up to 80,000 Roman spectators. Its massive elliptical structure remains the enduring symbol of Rome's imperial power and engineering genius.",
      city: "Rome",
      pexelsQuery: "Colosseum Rome ancient amphitheater",
    },
    {
      name: "Venice Canals",
      category: "Landmark",
      description: "Venice's 150 canals serve as the city's streets, navigated by gondolas, water taxis, and vaporetti through a labyrinth of Renaissance palaces and medieval bridges. The Grand Canal, lined with magnificent facades, is the city's main artery and one of the most scenic waterways in the world.",
      city: "Venice",
      pexelsQuery: "Venice canals gondola Italy",
    },
    {
      name: "Florence Cathedral",
      category: "Religious",
      description: "The Cathedral of Santa Maria del Fiore, crowned by Brunelleschi's extraordinary brick dome completed in 1436, dominates the Florence skyline and represents one of the greatest architectural achievements of the Renaissance. Its marble exterior of pink, green, and white is a masterpiece of Italian Gothic decoration.",
      city: "Florence",
      pexelsQuery: "Florence Cathedral Duomo dome Brunelleschi",
    },
    {
      name: "Amalfi Coast",
      category: "Nature",
      description: "A UNESCO World Heritage stretch of dramatic clifftop villages, lemon groves, and turquoise sea along southern Italy's Sorrentine Peninsula. Positano, Ravello, and Amalfi itself are perched on terraced hillsides cascading down to secluded coves.",
      city: "Amalfi",
      pexelsQuery: "Amalfi Coast Italy cliffside village",
    },
    {
      name: "The Vatican Museums",
      category: "Museum",
      description: "One of the world's great museum complexes housing the priceless art collections accumulated by the Catholic Church over centuries, culminating in Michelangelo's breathtaking Sistine Chapel ceiling. Visitors walk through over 54 galleries to reach this iconic masterpiece.",
      city: "Vatican City",
      pexelsQuery: "Vatican Museums Sistine Chapel Rome",
    },
    {
      name: "Pompeii",
      category: "Historic",
      description: "The remarkably preserved ancient Roman city buried by the eruption of Mount Vesuvius in 79 AD offers an unparalleled window into daily life two millennia ago. Streets, homes, bakeries, and even graffiti remain frozen in time across the sprawling UNESCO-listed site.",
      city: "Pompeii",
      pexelsQuery: "Pompeii ancient ruins Mount Vesuvius",
    },
  ],

  GBR: [
    {
      name: "Big Ben and the Houses of Parliament",
      category: "Landmark",
      description: "The iconic Gothic Revival clock tower officially known as the Elizabeth Tower rises above the Palace of Westminster on the banks of the Thames, and its Great Bell's chime is one of the most recognizable sounds in the world. Together with Parliament's ornate riverside facade, they form Britain's most photographed landmark.",
      city: "London",
      pexelsQuery: "Big Ben Houses of Parliament London Thames",
    },
    {
      name: "Stonehenge",
      category: "Historic",
      description: "A prehistoric monument of massive standing stones arranged in concentric rings on Salisbury Plain, built in stages between 3000 and 1500 BC and aligned with the solstice sunrise. Its purpose remains debated, but it is one of the world's most famous archaeological sites and a UNESCO World Heritage Site.",
      city: "Wiltshire",
      pexelsQuery: "Stonehenge prehistoric monument England",
    },
    {
      name: "The British Museum",
      category: "Museum",
      description: "One of the world's largest and most comprehensive museums, its collection spans two million years of human history across eight million objects from every corner of the globe. Highlights include the Rosetta Stone, the Elgin Marbles, and Egyptian mummies.",
      city: "London",
      pexelsQuery: "British Museum London Great Court",
    },
    {
      name: "Scottish Highlands",
      category: "Nature",
      description: "The rugged, untamed landscape of northern Scotland features dramatic glens, ancient lochs, and moody heather-clad mountains that have inspired legends for centuries. Loch Ness, Glen Coe, and Ben Nevis — Britain's highest peak — are among its most celebrated features.",
      city: "Inverness",
      pexelsQuery: "Scottish Highlands glens lochs landscape",
    },
    {
      name: "Tower of London",
      category: "Historic",
      description: "A historic castle on the north bank of the Thames, founded by William the Conqueror in 1066, that has served as a royal palace, prison, and treasury over its nearly thousand-year history. It houses the British Crown Jewels and is guarded by the ceremonial Yeomen Warders.",
      city: "London",
      pexelsQuery: "Tower of London castle historic",
    },
    {
      name: "Eden Project",
      category: "Entertainment",
      description: "A unique complex of giant geodesic biomes built inside a former china clay pit in Cornwall, housing thousands of plant species from tropical rainforest to Mediterranean climates. Beyond its botanical mission, it serves as a world-class entertainment and education venue.",
      city: "Cornwall",
      pexelsQuery: "Eden Project biome Cornwall England",
    },
  ],

  DEU: [
    {
      name: "Neuschwanstein Castle",
      category: "Historic",
      description: "The fairytale Bavarian castle commissioned by Ludwig II in 1869 perches on a rugged hill above the village of Hohenschwangau, inspiring Walt Disney's Sleeping Beauty Castle. Its turreted white limestone silhouette against the Alpine backdrop makes it Germany's most photographed building.",
      city: "Fussen, Bavaria",
      pexelsQuery: "Neuschwanstein Castle Bavaria Germany",
    },
    {
      name: "Brandenburg Gate",
      category: "Landmark",
      description: "An 18th-century neoclassical triumphal arch that stood at the heart of divided Berlin during the Cold War and today symbolizes German reunification and freedom. The Quadriga sculpture atop its columns is a defining icon of the German capital.",
      city: "Berlin",
      pexelsQuery: "Brandenburg Gate Berlin Germany",
    },
    {
      name: "Cologne Cathedral",
      category: "Religious",
      description: "A masterpiece of Gothic architecture that took over 600 years to complete, the Cologne Cathedral's twin spires soared as the world's tallest structure upon their completion in 1880. It houses the Shrine of the Three Kings and is Germany's most visited landmark.",
      city: "Cologne",
      pexelsQuery: "Cologne Cathedral Gothic spires Germany",
    },
    {
      name: "Black Forest",
      category: "Nature",
      description: "A dense mountain forest in southwest Germany famous for its dark fir trees, picturesque villages, cuckoo clocks, and the source of the Danube River. Scenic trails wind through valleys of waterfalls and farmhouses, inspiring the Brothers Grimm fairy tales.",
      city: "Freiburg im Breisgau",
      pexelsQuery: "Black Forest Germany fir trees landscape",
    },
    {
      name: "Pergamon Museum",
      category: "Museum",
      description: "Berlin's most visited museum houses monumental ancient structures including the reconstructed Pergamon Altar, the Ishtar Gate of Babylon, and the Market Gate of Miletus. The collection represents one of the finest assemblages of Hellenistic and Middle Eastern antiquities in the world.",
      city: "Berlin",
      pexelsQuery: "Pergamon Museum Berlin ancient artifacts",
    },
    {
      name: "Oktoberfest",
      category: "Entertainment",
      description: "The world's largest beer festival held annually in Munich's Theresienwiese grounds draws over six million visitors each year to massive beer tents, traditional Bavarian food, and fairground rides. The 16-day festival from late September to early October has been celebrated since 1810.",
      city: "Munich",
      pexelsQuery: "Oktoberfest Munich beer festival tents",
    },
  ],

  JPN: [
    {
      name: "Mount Fuji",
      category: "Nature",
      description: "Japan's highest and most iconic peak at 3,776 meters, the symmetrical volcanic cone is a UNESCO World Heritage Site and has inspired Japanese art and culture for centuries. Thousands climb to the summit during the official season, while the surrounding Fuji Five Lakes provide classic reflection views.",
      city: "Fujiyoshida, Yamanashi",
      pexelsQuery: "Mount Fuji Japan snow peak",
    },
    {
      name: "Fushimi Inari Taisha",
      category: "Religious",
      description: "The head shrine of the kami Inari is most famous for its thousands of vermilion torii gates that tunnel up through the forested slopes of Mount Inari. The atmospheric trail winds 4 km to the summit, passing fox statues and smaller shrines at every turn.",
      city: "Kyoto",
      pexelsQuery: "Fushimi Inari torii gates Kyoto Japan",
    },
    {
      name: "Tokyo Skytree",
      category: "Landmark",
      description: "At 634 meters, the Tokyo Skytree is the world's tallest tower and the second-tallest structure on Earth, offering panoramic views of the metropolis and beyond to Mount Fuji on clear days. The surrounding Skytree Town complex features an aquarium, planetarium, and high-end shopping.",
      city: "Tokyo",
      pexelsQuery: "Tokyo Skytree tower Japan skyline",
    },
    {
      name: "Arashiyama Bamboo Grove",
      category: "Nature",
      description: "A magical grove of towering bamboo stalks lining a stone pathway in the Arashiyama district on the western outskirts of Kyoto, one of Japan's most photographed natural landscapes. The grove is best experienced at dawn before the crowds arrive, when the rustling of the bamboo creates an ethereal atmosphere.",
      city: "Kyoto",
      pexelsQuery: "Arashiyama bamboo grove Kyoto Japan",
    },
    {
      name: "Hiroshima Peace Memorial",
      category: "Historic",
      description: "The Genbaku Dome, the only structure left standing near the atomic bomb's hypocenter in 1945, now stands as a UNESCO-listed symbol of peace and the consequences of nuclear war. The surrounding Peace Memorial Park contains museums, monuments, and an eternal flame that will burn until all nuclear weapons are abolished.",
      city: "Hiroshima",
      pexelsQuery: "Hiroshima Peace Memorial atomic bomb dome",
    },
    {
      name: "Shibuya Crossing",
      category: "Entertainment",
      description: "The world's busiest pedestrian intersection, where hundreds of people cross from all directions simultaneously during each traffic signal cycle, creating an exhilarating human spectacle. The surrounding Shibuya district pulsates with neon-lit fashion boutiques, restaurants, and nightlife.",
      city: "Tokyo",
      pexelsQuery: "Shibuya Crossing Tokyo intersection night",
    },
  ],

  THA: [
    {
      name: "Grand Palace",
      category: "Historic",
      description: "A dazzling complex of ornate buildings, gilded spires, and sacred temples that served as the official residence of the Thai kings from 1782 until 1925. Within its walls stands Wat Phra Kaew, the Temple of the Emerald Buddha, Thailand's most revered Buddhist site.",
      city: "Bangkok",
      pexelsQuery: "Grand Palace Bangkok Thailand golden temple",
    },
    {
      name: "Phi Phi Islands",
      category: "Beach",
      description: "A cluster of stunning limestone islands in the Andaman Sea, famous for their turquoise lagoons, towering cliffs, and vibrant coral reefs teeming with marine life. Maya Bay, nestled between soaring karst walls, became legendary as the filming location of 'The Beach.'",
      city: "Krabi Province",
      pexelsQuery: "Phi Phi Islands Thailand turquoise beach limestone",
    },
    {
      name: "Wat Arun",
      category: "Religious",
      description: "The Temple of Dawn, rising 79 meters above the Chao Phraya River, is adorned with fragments of Chinese porcelain and colorful glass that shimmer in the sunlight. It is one of Bangkok's most recognizable landmarks and is particularly beautiful at sunset when its tower glows orange.",
      city: "Bangkok",
      pexelsQuery: "Wat Arun Temple of Dawn Bangkok river",
    },
    {
      name: "Chiang Mai Old City",
      category: "Historic",
      description: "The historic heart of northern Thailand's cultural capital is a moat-encircled square mile containing over 30 ancient Buddhist temples dating back to the 13th-century Lanna Kingdom. The Sunday Walking Street market and nearby elephant sanctuaries make it one of Thailand's most beloved destinations.",
      city: "Chiang Mai",
      pexelsQuery: "Chiang Mai old city temple Thailand",
    },
    {
      name: "Railay Beach",
      category: "Beach",
      description: "Accessible only by boat due to the dramatic limestone cliffs surrounding it, Railay is one of Thailand's most breathtaking beaches with powder-white sand and emerald waters. Rock climbers from around the world come for its world-class routes scaling the sheer karst faces.",
      city: "Krabi",
      pexelsQuery: "Railay Beach Krabi Thailand limestone cliffs",
    },
    {
      name: "Doi Inthanon National Park",
      category: "Park",
      description: "Home to Thailand's highest peak at 2,565 meters, this national park in Chiang Mai Province encompasses misty cloud forests, spectacular waterfalls, and two royal pagodas built in honor of the King and Queen. Hill tribe villages and a remarkable variety of migratory birds make it a top destination for nature lovers.",
      city: "Chiang Mai",
      pexelsQuery: "Doi Inthanon national park Thailand waterfall misty",
    },
  ],

  GRC: [
    {
      name: "Acropolis of Athens",
      category: "Historic",
      description: "The ancient citadel rising above Athens contains the ruins of several historically significant buildings of the 5th century BC, most notably the Parthenon, a temple to the goddess Athena. As the birthplace of democracy and Western civilization, it is arguably the most important monument in the Western world.",
      city: "Athens",
      pexelsQuery: "Acropolis Athens Parthenon Greece",
    },
    {
      name: "Santorini Caldera",
      category: "Landmark",
      description: "The iconic white-washed villages of Oia and Fira cling to the rim of a vast volcanic caldera, offering incomparable views of the deep blue Aegean Sea and legendary sunsets. Santorini's distinctive Cycladic architecture and dramatic landscape make it one of the most photographed destinations on Earth.",
      city: "Santorini",
      pexelsQuery: "Santorini caldera white buildings blue dome Greece",
    },
    {
      name: "Meteora Monasteries",
      category: "Religious",
      description: "A series of medieval Eastern Orthodox monasteries built atop natural sandstone rock pillars that soar up to 400 meters above the Thessaly plain, a UNESCO World Heritage Site of exceptional natural and cultural significance. Six of the original 24 monasteries remain active and accessible by steps cut into the rock.",
      city: "Kalambaka",
      pexelsQuery: "Meteora monasteries rock pillars Greece",
    },
    {
      name: "Mykonos Windmills",
      category: "Landmark",
      description: "The row of 16th-century whitewashed windmills on the Kato Myli ridge above Mykonos Town is the island's defining symbol, originally built by the Venetians to mill wheat from the Aegean winds. Below them, the colorful fishing boats and boutiques of Little Venice create one of Greece's most charming harbor scenes.",
      city: "Mykonos",
      pexelsQuery: "Mykonos windmills Greece white Cyclades",
    },
    {
      name: "Delphi Archaeological Site",
      category: "Historic",
      description: "The sanctuary of the ancient Greek god Apollo at Delphi was considered the center of the world in antiquity, where pilgrims sought the counsel of the famous Oracle. Dramatic mountain scenery frames the ruins of the Temple of Apollo, the theater, and the stadium on the slopes of Mount Parnassus.",
      city: "Delphi",
      pexelsQuery: "Delphi ancient ruins Oracle Greece mountains",
    },
    {
      name: "Navagio Beach",
      category: "Beach",
      description: "Also known as Shipwreck Beach, this isolated cove on the island of Zakynthos is accessible only by boat through towering white limestone cliffs and holds the rusting wreck of a smuggler's ship on brilliant white sand. The vivid contrast of the azure water, white cliffs, and orange shipwreck makes it one of Greece's most spectacular beaches.",
      city: "Zakynthos",
      pexelsQuery: "Navagio Shipwreck Beach Zakynthos Greece",
    },
  ],

  TUR: [
    {
      name: "Hagia Sophia",
      category: "Religious",
      description: "Originally built as a Christian cathedral in 537 AD, converted to a mosque in 1453, and turned into a museum in 1934 before being reconverted to a mosque in 2020, Hagia Sophia has been a witness to over 1,500 years of history. Its massive dome, soaring 55 meters above the floor, was the world's largest for nearly a thousand years and remains a masterpiece of Byzantine engineering.",
      city: "Istanbul",
      pexelsQuery: "Hagia Sophia Istanbul Turkey dome",
    },
    {
      name: "Cappadocia",
      category: "Nature",
      description: "A surreal landscape of volcanic rock formations called 'fairy chimneys,' ancient cave dwellings, and underground cities carved into the soft tuff of central Anatolia. Hot air balloon flights at dawn over the otherworldly valleys of Goreme are among the most magical travel experiences in the world.",
      city: "Goreme, Nevsehir",
      pexelsQuery: "Cappadocia hot air balloon fairy chimneys Turkey",
    },
    {
      name: "Topkapi Palace",
      category: "Historic",
      description: "The vast Ottoman imperial palace that served as the administrative center of the empire and residence of the sultans for nearly 400 years, now a museum housing priceless imperial treasures and holy relics. Its Harem complex, pavilions, and the breathtaking view over the Bosphorus and Golden Horn make it Istanbul's most compelling museum.",
      city: "Istanbul",
      pexelsQuery: "Topkapi Palace Istanbul Ottoman museum",
    },
    {
      name: "Pamukkale Terraces",
      category: "Nature",
      description: "Meaning 'cotton castle' in Turkish, Pamukkale's gleaming white terraced pools of mineral-rich thermal waters cascade down a hillside in western Turkey like a frozen waterfall. The adjacent ancient Roman city of Hierapolis, with its well-preserved theater and necropolis, is included in the UNESCO World Heritage Site.",
      city: "Denizli",
      pexelsQuery: "Pamukkale thermal pools white terraces Turkey",
    },
    {
      name: "Ephesus",
      category: "Historic",
      description: "One of the best-preserved ancient cities in the Mediterranean world, Ephesus was a thriving Greek and Roman port city that once housed the Library of Celsus and the Temple of Artemis, one of the Seven Wonders of the Ancient World. Its marble-paved colonnaded streets, grand theater, and monumental facades offer an astonishing glimpse into antiquity.",
      city: "Selcuk, Izmir",
      pexelsQuery: "Ephesus ancient ruins Library of Celsus Turkey",
    },
    {
      name: "Bosphorus Strait",
      category: "Landmark",
      description: "The narrow waterway dividing Istanbul between Europe and Asia is one of the world's most strategically important and visually dramatic straits, lined with Ottoman palaces, waterfront mansions, and fortress towers. A boat cruise along the Bosphorus reveals Istanbul's layered history in a way no land-based tour can match.",
      city: "Istanbul",
      pexelsQuery: "Bosphorus Strait Istanbul bridge Europe Asia",
    },
  ],
};
